### ISSUE TITLE
Landing page button ui

### ISSUE THREAD

**Issue by capricorn-32** [luraproject/luraproject.org#2]
**Describe the bug**
There is not gap between svg and text. Compared to text, svg size bigger. 
svg and text is not aligned - ceter as if now.

**To Reproduce**
visist to https://luraproject.org/

**Expected behavior**
svg and text should be in center
reduce svg size from 6px to 5px 

**Additional context**
![rename bug](https://github.com/user-attachments/assets/a7d8ef20-34c7-49a7-9c39-a5a87f5d3d37)

**Comment by kpacha** [comment]
Thanks for the heads up! contributions are always welcome, so feel free to create as many PR as you want

**Comment by seniorLikeToCode** [comment]
hey @kpacha I create PR.
